name: 'Test Reporter'

on:
  workflow_run:
    workflows: ['Test CI']
    types:
      - completed
jobs:
  Report:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Reporter
        path: '*.xml'
        reporter: java-junit
        fail-on-error: false
