name: Test CI

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
 
jobs:
  Handle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Demo
      uses: actions/github-script@v6
      with:
        script: |
          const runInfo = await github.rest.checks.listForRef({
            ref: context.ref,
            owner: context.repo.owner,
            repo: context.repo.repo
          })
          console.log(runInfo)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Run test
      id: unitTest
      run: mvn test
    - name: Upload test report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports/*.xml
    - name: Code Coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: jacoco.xml
        directory: ./target/site/jacoco/
    - name: Notify pusher (Success)
      if: github.event_name == 'push'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_HOST }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: '⭐ [GITHUB BOT][SUCCESS] Push report'
        from: Github Action Bot
        to: ${{ secrets.SMTP_RECEIVER }}
        body: |
          Push created by ${{ github.event.pusher.name }} has been succeeded.
          Detail: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
    - name: Notify pusher (Failed, Other cases)
      if: failure() && github.event_name == 'push' && steps.unitTest.outcome != 'failure'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_HOST }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: '🔥 [GITHUB BOT][FAILED] Push report'
        from: Github Action Bot
        to: ${{ secrets.SMTP_RECEIVER }}
        body: |
          Push created by ${{ github.event.pusher.name }} has been failed.
          Reason: Something went wrong.
          Detail: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
  Push_Reporter:
    needs: [Handle]
    if: failure() && needs.Handle.result == 'failure' && github.event_name == 'push'
    uses: ./.github/workflows/test-reporter-push.yml
    secrets:
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      SMTP_RECEIVER: ${{ secrets.SMTP_RECEIVER }}