name: Push Reporter

on: 
  workflow_call:
    secrets:
      SMTP_HOST:
        required: true
      SMTP_PORT:
        required: true
      SMTP_USERNAME:
        required: true
      SMTP_PASSWORD:
        required: true
      SMTP_RECEIVER:
        required: true
 
jobs:
  Reporter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download test report
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: artifact
      - name: Process report
        id: reportAction
        uses: dorny/test-reporter@v1
        with:
          name: Unit test result
          path: 'artifact/*.xml'
          reporter: java-junit
          fail-on-error: false
      - name: Get HTML result
        if: github.event_name == 'push'
        uses: actions/github-script@v6
        with:
          script: |
            const runInfo = await github.rest.actions.listJobsForWorkflowRun({
              run_id: context.runId,
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            const testResult = runInfo.data.jobs.find(item => item.name === 'Unit test result')
            const htmlUrl = testResult.html_url
            core.exportVariable('htmlUrl', htmlUrl)
      - name: Notify pusher (Failed test)
        if: github.event_name == 'push'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: '🔥 [GITHUB BOT][FAILED] Push report (Unit test failed)'
          from: Github Action Bot
          to: ${{ secrets.SMTP_RECEIVER }}
          body: |
            Push created by ${{ github.event.pusher.name }} has been failed.
            Reason: Unit test failed.
            Detail: ${{ env.htmlUrl }}